### ISSUE TITLE
Unexpected token $ in JSON

### ISSUE THREAD

**Issue by retorquere** [fiduswriter/biblatex-csl-converter#80]
When parsing this entry:

```
@inproceedings{Poole2017,
author = {Poole, Robert W and Foundation, Reason},
booktitle = {Transportation Research Board, 96th Annual Meeting},
file = {:C$\backslash$:/Users/amitrani/Documents/Mendeley/Poole, Foundation - 2017 - Enhanced Bus and Managed Arterials.pdf:pdf},
pages = {1--14},
title = {{Enhanced Bus and Managed Arterials}},
volume = {9426},
year = {2017}
}
```

I'm getting an error:

```
SyntaxError: Unexpected token $ in JSON at position 605
    at JSON.parse (<anonymous>:null:null)
    at BibLatexParser.cleanDB (/home/emile/github/bbt/better-bibtex/node_modules/biblatex-csl-converter/lib/import/biblatex.js:918:31)
    at BibLatexParser.get (/home/emile/github/bbt/better-bibtex/node_modules/biblatex-csl-converter/lib/import/biblatex.js:928:18)
    at importReferences (/home/emile/github/bbt/better-bibtex/minitests/import.coffee:14:22)
    at Object.<anonymous> (/home/emile/github/bbt/better-bibtex/minitests/import.coffee:26:14)
    at Object.<anonymous> (/home/emile/github/bbt/better-bibtex/minitests/import.coffee:1:1)
    at Module._compile (module.js:569:30)
    at Object.exports.run (/home/emile/github/bbt/better-bibtex/node_modules/coffeescript/lib/coffee-script/coffee-script.js:173:23)
    at compileScript (/home/emile/github/bbt/better-bibtex/node_modules/coffeescript/lib/coffee-script/command.js:224:29)
    at compilePath (/home/emile/github/bbt/better-bibtex/node_modules/coffeescript/lib/coffee-script/command.js:174:14)
    at Object.exports.run (/home/emile/github/bbt/better-bibtex/node_modules/coffeescript/lib/coffee-script/command.js:98:20)
    at Object.<anonymous> (/home/emile/github/bbt/better-bibtex/node_modules/coffeescript/bin/coffee:15:45)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

No doubt that is a funky path in the `file` field, but this is a live reference I've received.

**Comment by retorquere** [comment]
Would it be sufficient to change [this line](https://github.com/fiduswriter/biblatex-csl-converter/blob/master/src/import/biblatex.js#L791) to `.replace(/\u0871/,'\\\\')`? I get no parse errors if O do that.

**Comment by johanneswilm** [comment]
Yep, same I ended up doing :)
